dist: xenial
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "vAMnsB+0E9i0SWOttnuQAxq8czJ1LWf1z3ahg3nLPIbqSL40+O7Y6IzsKs/w/0TewZ9eAzD/33EjeygFH2uLt+JZi
rCykVe7u9nyYU9BKCk/bFEkf6sqiMgJSLg+ZULdPnP1jO6bU4v0R2iPKkEBgc0fuqh/CvoCxKSepS2JNGohVylgFNiBJaQrToEyX
ZhDXyhCAcc+hBQ4e3qGhsDlPGUnwpjexahvywLGGFH5xAFXoZBb/ZMIEPCHNnozDOjhQ6MHz+lm5VXubQ+NWTwRpyICMbEH5lawp
odzJ4JRCtL14tzpKbRJqeI1xg7kg62J0CiVROTm/qu/+LW19OoX0logG8wWySWWX5EJZ5rIiCNswBbwK6v4rEW3OupHsBwNO0Z8b
NYD+SEf+2HfnxqfC1j7STaBoxv0OdQXsZH7yr59vK7T6Cv4cJ4sntfWlwc6YcmRsl0rd8EjjbLGtwGWXQRuOAJ8zrO029Xup/OXm
zfeflXsYGDsAjh9hHowiNlfa01kOzLFlP9thDcWubz4s2VZWDDjBzlnYu86S2FyMkXU7ZPQcCmKgtSwYxci7k7owJZc0SYAdWBHh
ANGf1BoobYL6iX7TZVW64ij9+WOxGhfkfSevZK+Wyeq1PI/4dirFqre/g9cOcdK174DauwnZChTyWh+aEro2fbSSBfieKc="
    
install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: oraclejdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
  