dist: xenial
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "vAMnsB+0E9i0SWOttnuQAxq8czJ1LWf1z3ahg3nLPIbqSL40+O7Y6IzsKs/w/0TewZ9eAzD/33EjeygFH2uLt+JZi
rCykVe7u9nyYU9BKCk/bFEkf6sqiMgJSLg+ZULdPnP1jO6bU4v0R2iPKkEBgc0fuqh/CvoCxKSepS2JNGohVylgFNiBJaQrToEyX
ZhDXyhCAcc+hBQ4e3qGhsDlPGUnwpjexahvywLGGFH5xAFXoZBb/ZMIEPCHNnozDOjhQ6MHz+lm5VXubQ+NWTwRpyICMbEH5lawp
odzJ4JRCtL14tzpKbRJqeI1xg7kg62J0CiVROTm/qu/+LW19OoX0logG8wWySWWX5EJZ5rIiCNswBbwK6v4rEW3OupHsBwNO0Z8b
NYD+SEf+2HfnxqfC1j7STaBoxv0OdQXsZH7yr59vK7T6Cv4cJ4sntfWlwc6YcmRsl0rd8EjjbLGtwGWXQRuOAJ8zrO029Xup/OXm
zfeflXsYGDsAjh9hHowiNlfa01kOzLFlP9thDcWubz4s2VZWDDjBzlnYu86S2FyMkXU7ZPQcCmKgtSwYxci7k7owJZc0SYAdWBHh
ANGf1BoobYL6iX7TZVW64ij9+WOxGhfkfSevZK+Wyeq1PI/4dirFqre/g9cOcdK174DauwnZChTyWh+aEro2fbSSBfieKc="

addons:
  sonarcloud:
    organization: "phax-github"
    token:
      secure: "l7cLq+3JszCxN+glIFZ+jUbkqarxa3qbpF9yc2Wrn5aniM6dgI57VodXHCSzmTKBjQZCMe9dgUNKj0UfWNQUaNd/WRn2JFYlda35KvXlK2+ViVLCSeqrNfb0Cq5KxfK
wkSNQSGZcl3BFdQydw97Ix4gTai4u52k6xvDI+YKRJAAidf0jOid122dlh29DuKXPlmlYav19ScNQT8sf7t/EjKsGMmn9us2KPMasn+uXE3CPPwQ5KKirdwbSX8Ab8HFn1UfKLmxTj
htZxOM1pafY9awvhaeyk0/nvBo5JfMgLNMqnriMJTHFO+NlYFeCCd9gU5KdtRJpsDA3HRaWHJd8kBMp5xT/muQsxA2mWFoak6WpMiwW6qq8XJmmXBoyPrzfjsyVw1qJ0G1vGdwazL3
6vW/ZgU6rb8MhfJvfRQuQa+TZ88PXR1miCM9vjzfpGKfYlfBRtfPdedPlgtn6jgiVe18/dFs0n89I2s/MXCvfKNUwtSN8EjwwWNnTR9hXUgVNMdFUjdcAPv/m7mplKl7mQw58M/CX7
2g9BeEj2i4Ml4uZJO0ZcLGgImryoj9NvvHxCIXQL0iuQDTwP5nnKZQ2m+jQm4XcJJk84XIFTPE/RCdFQY747UcLRrcDc1hqmspI1NN3fdwv7pc9QAc24yuXDnWpW0Dr12xW/xCoc/I
oMNE="

install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B -P coverage sonar:sonar
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk14
      script:
        - mvn test -B
  